#!/usr/bin/env bash
# Reset the user-service decomposition regression test to its initial state.
# Run this before each pipeline run.
#
# What this does:
#   1. Creates a fresh target repo at /tmp/ai-builder-test-user-service/
#   2. Installs the task management system and CLAUDE.md
#   3. Places the user-service task in in-progress/ (simulating Oracle)
#   4. Restores the job document from the template into the output dir
#   5. Clears any previous pipeline artifacts from the output dir

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DIR/../../.." && pwd)"
WORK="$DIR/work"

TARGET_REPO="/tmp/ai-builder-test-user-service"
OUTPUT_DIR="/tmp/ai-builder-test-user-service-output"
EPIC="main"
TASK_NAME="user-service"

echo "=== Resetting user-service regression test ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Fresh target repo
# ---------------------------------------------------------------------------

echo "[1/5] Creating fresh target repo at $TARGET_REPO ..."
rm -rf "$TARGET_REPO"
mkdir -p "$TARGET_REPO"

# ---------------------------------------------------------------------------
# 2. Install task management system and CLAUDE.md
# ---------------------------------------------------------------------------

echo "[2/5] Installing task management system ..."
"$REPO_ROOT/target/setup-project.sh" "$TARGET_REPO" --epic "$EPIC"
"$REPO_ROOT/target/init-claude-md.sh" "$TARGET_REPO"

# ---------------------------------------------------------------------------
# 3. Create task and place it in in-progress (simulating Oracle)
# ---------------------------------------------------------------------------

echo "[3/5] Creating user-service task in in-progress/ ..."
SCRIPTS="$TARGET_REPO/project/tasks/scripts"

"$SCRIPTS/new-task.sh" --epic "$EPIC" --folder draft --name "$TASK_NAME"

# Find the generated task directory (it gets a short hash prefix)
TASK_DIR=$(find "$TARGET_REPO/project/tasks/$EPIC/draft" -maxdepth 1 -type d -name "*-$TASK_NAME" | head -1)
if [[ -z "$TASK_DIR" ]]; then
    echo "ERROR: Could not find created task directory for $TASK_NAME"
    exit 1
fi
TASK_FULL_NAME="$(basename "$TASK_DIR")"

# Write the task description
cat > "$TASK_DIR/README.md" <<'TASKEOF'
# Task: user-service

| Field    | Value          |
|----------|----------------|
| Status   | in-progress    |
| Epic     | main           |
| Tags     | regression-test |
| Parent   | —              |
| Priority | MED            |

## Description

Build a user management HTTP service in Go.

**Requirements:**
- Language: Go
- Port: `8080`
- Routes:
  - `POST /users` — create a user, return the created user with generated ID
  - `GET /users/{id}` — retrieve user by ID; return 404 if not found
  - `PUT /users/{id}` — update user by ID; return 404 if not found
  - `DELETE /users/{id}` — delete user by ID; return 404 if not found
- Response format: JSON
- Storage: in-memory (no database, no persistence between restarts)
- No authentication or authorisation

## Subtasks

<!-- subtask-list-start -->
<!-- subtask-list-end -->

## Notes

_None._
TASKEOF

"$SCRIPTS/move-task.sh" --epic "$EPIC" --name "$TASK_FULL_NAME" --from draft --to in-progress

echo "    task: $TASK_FULL_NAME"

# ---------------------------------------------------------------------------
# 4. Restore job document from template
# ---------------------------------------------------------------------------

echo "[4/5] Restoring job document from template ..."
mkdir -p "$OUTPUT_DIR"
cp "$WORK/JOB-user-service.md.template" "$OUTPUT_DIR/JOB-user-service.md"
# Write current-job.txt so the orchestrator knows the initial job doc path
# (simulates what Oracle would do before invoking the pipeline).
echo "$OUTPUT_DIR/JOB-user-service.md" > "$OUTPUT_DIR/current-job.txt"

# ---------------------------------------------------------------------------
# 5. Clear previous pipeline artifacts from output dir
# ---------------------------------------------------------------------------

echo "[5/5] Clearing previous pipeline artifacts ..."
rm -f  "$OUTPUT_DIR/execution.log"
rm -rf "$OUTPUT_DIR/logs"
# Remove any job docs generated by a previous pipeline run (keep only the
# seeded JOB-user-service.md and current-job.txt we just wrote).
find "$OUTPUT_DIR" -maxdepth 1 -name "JOB-*.md" \
    ! -name "JOB-user-service.md" -delete

echo ""
echo "=== Reset complete ==="
echo ""
echo "Target repo : $TARGET_REPO"
echo "Output dir  : $OUTPUT_DIR"
echo ""
echo "Run the pipeline:"
echo "  python3 $REPO_ROOT/ai-builder/orchestrator/orchestrator.py \\"
echo "      --target-repo $TARGET_REPO \\"
echo "      --output-dir  $OUTPUT_DIR \\"
echo "      --epic        $EPIC"
echo ""
echo "Then run the gold test:"
echo "  cd $DIR/gold && go test -tags regression ./..."
